Tentative - костяк приложения с одним хэндлером GetAllBook
PavelKaratkevich/book_store pull request #1
Opened 2021-12-30 20:33 UTC by PavelKaratkevich

Ренат, здравствуйте!

Изучил литературу и решил попробовать написать костяк приложения (пока только с одним хэндлером GetAllBook).

Разбил папки по следующему принципу:
- **cmd** - вход в программу
- **internal** - код программы:
- internal/domain - объявляет модель Book
- internal/repositoryDB/postgresDB - это package, который имплементирует интерфейс и объявляет функции, которые взаимодействуют с БД PostgreSQL. При необходимости поменять БД я создам новый package, в котором имплементирую методы интерфейса и объявлю функции взаимодействия с новой БД.
- internal/dto - модель DTO
- internal/service - use case layer
- internal/handler - хэндлер, взаимодействующий с пользователем.

Вывод получается следующий:
![image](https://user-images.githubusercontent.com/84831116/147785953-79cebc6f-fb51-4854-9b0a-ddb97b288919.png)

Понимаю, что мое решение, скорее всего, нуждается в серьезных корректировках или же полном переписывании. Тем не менее, буду очень благодарен за возможность обсудить такой подход!

С уважением,
Павел

2022-01-03 07:21 UTC, rast1025 commented on internal/domain/domain.go
> +func (b Book) ToDto() dto.Book {
remove dto

2022-01-03 07:22 UTC, rast1025 commented on internal/repositoryDB/postgresDB/instructions.sh
> +CREATE TABLE books_store (
Better add `IF NOT EXISTS`

2022-01-03 09:12 UTC, PavelKaratkevich commented on internal/domain/domain.go
> +func (b Book) ToDto() dto.Book {
done with commit "remove DTO" 3180b1d

2022-01-03 09:12 UTC, PavelKaratkevich commented on internal/repositoryDB/postgresDB/instructions.sh
> +CREATE TABLE books_store (
done with commit "Update instructions.sh" 8fa64cf

2022-01-05 07:55 UTC, PavelKaratkevich commented
@rast1025 Ринат, здравствуйте!

- Внес правки, которые обсуждали с Вами в понедельник.
- Добавил CORS, Logger middleware и проверку наличия переменных окружения (check env).
- Добавил Docker, Docker-compose.yml файлы. Приложение запускается при запуске docker-compose up, однако, база данных не работает. В этом заключается основная сложность: я пока не понимаю, как связать мою локальную БД с докером.

Основной вопрос, на который пока не нашел ответ:
- Я должен привязать существующую локальную БД к Docker-compose (если да, то как?) или же запустить в Docker-compose новый инстанс БД (если да, то как? и как в таком случае переделать серверную часть приложения, которая запускает локальную БД по адресу postgres://postgres:%s@%s:%s/%s?sslmode=disable"?)

2022-01-10 08:24 UTC, rast1025 requested changes

2022-01-10 08:24 UTC, rast1025 commented on cmd/myapp.go
> +package main
Add an api folder inside cmd.

2022-01-10 08:24 UTC, rast1025 commented on internal/domain/domain.go
> +	Year    string         `json:"Year" db:"year" binding:"required"`
Let's add date validation to `Year` field

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +	id, _ := strconv.Atoi(ctx.Param("id"))
always check for errors

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +	id, _ := strconv.Atoi(ctx.Param("id"))
return 400 in case of error

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +func (bh BookHandler) DeleteBookByItsIdNumber(ctx *gin.Context) {
I think `DeleteById` func name is explicit enough

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +	id, _ := strconv.Atoi(ctx.Param("id"))
Same, check for error

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +		ctx.JSON(http.StatusNotFound, "ID not found")
is it a json?

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +	id, _ := strconv.Atoi(ctx.Param("id"))
same, check error

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +		ctx.JSON(http.StatusInternalServerError, "Internal error")
don't forget to `return`

2022-01-10 08:24 UTC, rast1025 commented on internal/injection/injection.go
> +	g := gin.Default()
you can register endpoints in BookHandler

2022-01-10 08:24 UTC, rast1025 commented on internal/injection/injection.go
> +	g := gin.Default()
https://github.com/gin-gonic/gin#grouping-routes

2022-01-10 08:24 UTC, rast1025 commented on internal/repositoryDB/postgresDB/postgres.go
> +	db_name := os.Getenv("DB_NAME")
Check envs on start-up

2022-01-10 08:24 UTC, rast1025 commented on Dockerfile
> +COPY --from=builder /app/ /app/
add `.env` file and `instructions.sql` to 2nd stage as well

2022-01-10 08:24 UTC, rast1025 commented on internal/handler/handlers.go
> +		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Unknown error"})
log errors

2022-01-10 08:24 UTC, rast1025 commented on internal/middleware/middleware.go
> +		log.Printf("Host: %v, Request method received: %s, Request path: %s", c.Request.Host, c.Request.Method, c.Request.URL.Path)
add status code as well

2022-01-10 08:24 UTC, rast1025 commented on internal/repositoryDB/postgresDB/postgres.go
> +func (b BookRepositoryPostgreSQL) GetBooks() ([]domain.Book, *error) {
no need to return pointer to an error. just error is enough

2022-01-11 06:27 UTC, PavelKaratkevich commented on cmd/myapp.go
> +package main
done

2022-01-11 06:27 UTC, PavelKaratkevich commented on internal/domain/domain.go
> +	Year    string         `json:"Year" db:"year" binding:"required"`
done

2022-01-11 06:30 UTC, PavelKaratkevich commented on internal/handler/handlers.go
> +		ctx.JSON(http.StatusNotFound, "ID not found")
fixed with gin.H{"error": "ID not found"}

2022-01-11 06:31 UTC, PavelKaratkevich commented on internal/handler/handlers.go
> +		ctx.JSON(http.StatusInternalServerError, "Internal error")
done

2022-01-11 06:32 UTC, PavelKaratkevich commented on internal/injection/injection.go
> +	g := gin.Default()
done - grouped routes via
`routes := g.Group("/books", middleware.CheckToken())`

2022-01-11 06:33 UTC, PavelKaratkevich commented on internal/repositoryDB/postgresDB/postgres.go
> +	db_name := os.Getenv("DB_NAME")
done with function checkEnvVars(s ...string)

2022-01-11 06:33 UTC, PavelKaratkevich commented on Dockerfile
> +COPY --from=builder /app/ /app/
done

2022-01-11 06:43 UTC, PavelKaratkevich commented on internal/handler/handlers.go
> +		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Unknown error"})
done

2022-01-11 06:44 UTC, PavelKaratkevich commented on internal/handler/handlers.go
> +	id, _ := strconv.Atoi(ctx.Param("id"))
done

2022-01-11 06:44 UTC, PavelKaratkevich commented on internal/handler/handlers.go
> +	id, _ := strconv.Atoi(ctx.Param("id"))
done

2022-01-11 06:44 UTC, PavelKaratkevich commented on internal/handler/handlers.go
> +func (bh BookHandler) DeleteBookByItsIdNumber(ctx *gin.Context) {
func has been renamed

2022-01-11 06:44 UTC, PavelKaratkevich commented on internal/handler/handlers.go
> +	id, _ := strconv.Atoi(ctx.Param("id"))
done

2022-01-11 06:47 UTC, PavelKaratkevich commented on internal/middleware/middleware.go
> +		log.Printf("Host: %v, Request method received: %s, Request path: %s", c.Request.Host, c.Request.Method, c.Request.URL.Path)
done

2022-01-11 06:56 UTC, PavelKaratkevich commented on internal/repositoryDB/postgresDB/postgres.go
> +func (b BookRepositoryPostgreSQL) GetBooks() ([]domain.Book, *error) {
done - removed pointers to errors across the app

2022-01-11 11:29 UTC, rast1025 commented
looks good to me

2022-02-14 05:35 UTC, merged